cookie:
  expiry_days: 0
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    ayoung:
      name: "\uC544\uC601"
      password: $2b$12$P97Kn2a2oZn1ZBJSaIeq5eWiuRbpo1wsvZ1qA4ZNbz2kXt4N6sCXC
    sunkyu:
      name: "\uC120\uADDC"
      password: $2b$12$ZUvVzjjFN9ChppQXIMgDN./7oHXLDoCeNRxkc/vNvKt52q2oaFH..
preauthorized:
  emails:
  - melsby@gmail.com
